### ISSUE TITLE
Feature Request: Add Line number as an available format item

### ISSUE THREAD

**Issue by umm7yass** [AnotherSadGit/Prog_PowerShellLogger#1]
It would be nice to be able to include the line number in logs as well.

**Comment by OneEyedSi** [comment]
By line number you mean the line number within a log file?

So if we start a new log file, or overwrite an existing one, the line number would start at 1 again?

**Comment by umm7yass** [comment]
By line number, I mean the line number of the invocation. So if the write-logmessage was on line 42 of a script, the 42 would be returned.

**Comment by OneEyedSi** [comment]
Added in v3.1.0.  New MessageFormat placeholder is `{CallerLineNumber}`.
