### ISSUE TITLE
Import-Module fails with error "ParserError: Missing expression after ','."

### ISSUE THREAD

**Issue by OneEyedSi** [AnotherSadGit/Prog_PowerShellLogger#2]
Full error message: 

> ParserError: Missing expression after ','.
> Import-Module: The module to process 'Pslogg.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Temp\Pslogg\2.0.0\Pslogg.psd1' was not processed because no valid module was found in any module directory.

**Comment by OneEyedSi** [comment]
Import-Module with verbose flag shows the import process appears to be parsing the Pslogg.psd1 file okay but failing when loading Pslogg.psm1.

Opening Pslogg.psm1 in Visual Studio Code shows several lines where the Parameter attribute wraps onto a new line have Unicode character U+fffd at the start of the second line.

**Comment by AnotherSadGit** [comment]
Fixed in v2.1.1.

**Comment by OneEyedSi** [comment]
Fixed in v2.1.1.
